source 'https://rubygems.org'

ruby '2.4'

gem 'rails'
gem 'sprockets'
gem 'sass-rails'
gem 'coffee-rails'
gem 'uglifier'
gem 'jbuilder'
gem 'turbolinks'
gem 'dropzonejs-rails'
gem 'rails_autolink'
gem 'bcrypt'
gem 'sanitize'
gem 'rack-attack'
gem 'rails-i18n'
gem 'http_accept_language'
gem 'font-awesome-rails'
gem 'doorkeeper'
gem 'doorkeeper-i18n'
gem 'bulk_insert'
gem 'pg'  # NOT SUPPORT MYSQL / MARIADB
gem 'carrierwave'
gem 'carrierwave-i18n'
# gem 'carrierwave-qiniu'
# gem 'carrierwave-upyun'
# gem 'carrierwave-aliyun'
# gem 'carrierwave-aws'
# gem 'carrierwave-azure'
gem 'carrierwave-bombshelter'
gem 'mini_magick'
gem 'rucaptcha'
gem 'recaptcha', require: "recaptcha/rails"
gem 'letter_avatar'
gem 'devise'
gem 'devise-encryptable'
gem 'simple_token_authentication'
gem 'devise_invitable'
gem 'devise-two-factor'
gem 'devise-async'
gem 'notifications'
# gem 'rails-push-notification'
gem 'rpush'
gem 'rpush-redis'
gem 'rqrcode'
gem 'action-store'
gem 'kaminari'
gem 'elasticsearch-model'
gem 'elasticsearch-rails'
gem 'omniauth'
gem 'omniauth-github'
gem 'omniauth-google-oauth2'
gem 'omniauth-facebook'
gem 'omniauth-twitter'
gem 'cancancan'
gem 'audited'
gem 'figaro'
gem 'faker'
gem 'redis'
gem 'redis-namespace'
gem 'redis-objects'
gem 'second_level_cache'
gem 'rails-settings-cached'
gem 'html-pipeline'
gem 'html-pipeline-rouge_filter'
gem 'redcarpet'
gem 'auto-space'
gem 'sidekiq'
gem 'social-share-button'
gem 'simple_form'
gem 'postmark'
gem 'postmark-rails'
gem 'kgio'
gem 'dalli'
gem 'puma'
gem 'rack-cors', require: 'rack/cors'
gem 'rack-utf8_sanitizer'
gem 'exception-track'
gem 'status-page'
gem 'bundler-audit', require: false
gem 'homeland-wiki'
gem 'homeland-note'
gem 'google-analytics-rails'
gem 'acts-as-taggable-on'
gem "breadcrumbs_on_rails"
gem 'rails_amp'
gem 'rails-latex'
gem 'piwik_analytics'
gem 'valid_email2'
gem 'snowflake-id'
gem 'sentry-raven'
gem 'sdoc'

group :development do
  gem 'derailed'
  # Better Errors
  gem 'better_errors'
  gem 'spring'
  gem 'spring-commands-rspec'
end

group :development, :test do
  gem 'listen'
  gem 'rubocop', '0.47.1', require: false
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'letter_opener'
  gem 'yard'
  gem 'codecov', require: false
end
